from setuptools import setup, find_packages

setup(
    name="uncertainty_aware_ids",
    version="1.0.0",
    description="Uncertainty-Aware and Robust Intrusion Detection: A Novel Bayesian Ensemble Transformer Framework Informed by In-Context Learning",
    author="Research Team",
    author_email="research@example.com",
    packages=find_packages(),
    install_requires=[
        "torch>=2.0.0",
        "torchvision>=0.15.0",
        "numpy>=1.21.0",
        "pandas>=1.3.0",
        "scikit-learn>=1.0.0",
        "matplotlib>=3.5.0",
        "seaborn>=0.11.0",
        "tqdm>=4.62.0",
        "tensorboard>=2.8.0",
        "scipy>=1.7.0",
        "networkx>=2.6.0",
        "plotly>=5.0.0",
        "wandb>=0.12.0",
        "jupyter>=1.0.0",
        "ipykernel>=6.0.0",
        "pyyaml>=6.0",
    ],
    python_requires=">=3.8",
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.8",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Programming Language :: Python :: 3.11",
    ],
)
